# docker-compose.yml   C:\Users\benit\Downloads\Tienda-Online-main\BackendDj\docker-compose.yml
version: '3.9'

services:
  django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
