# docker-compose.yml

version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_main
    environment:
      POSTGRES_DB: themauses
      POSTGRES_USER: themauses_user
      POSTGRES_PASSWORD: feVslwNMHceEdHBpUnUsHZhYfbnjb5EM
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
